#!python
import warnings
import os
import sys
import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir)

from checkov.main import run

if __name__ == '__main__':
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=SyntaxWarning)
        sys.exit(run())
